abstract: ~
author: Masatoshi Mizuno E<lt>mizunoE<64>bomcity.comE<gt>
build_requires: 
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-Template-Associate-FormField
no_index: 
  directory: 
    - inc
    - t
version: 0.10
