---
name: HTML-Template-Associate-FormField
version: 0.12
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: lib/HTML/Template/Associate/FormField.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Template: 2.9
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  HTML::Template::Associate::FormField:
    file: lib/HTML/Template/Associate/FormField.pm
    version: 0.12
  HTML::Template::Associate::FormField::Hidden:
    file: lib/HTML/Template/Associate/FormField.pm
  HTML::Template::Associate::FormField::Param:
    file: lib/HTML/Template/Associate/FormField.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
